group: bluezone
sudo: required
dist: trusty
language: node_js
node_js:
  - 'lts/*'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run test:ci-cypress
